In [107]:
%pip install requests==2.32.3 beautifulsoup4==4.12.3 pandas==2.2.2 xhtml2pdf==0.2.16

Requirement already satisfied: requests==2.32.3 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (2.32.3)
Requirement already satisfied: beautifulsoup4==4.12.3 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (4.12.3)
Requirement already satisfied: pandas==2.2.2 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (2.2.2)
Requirement already satisfied: xhtml2pdf==0.2.16 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (0.2.16)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from requests==2.32.3) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from requests==2.32.3) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from requests==2.32.3) (2.2.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from requests==2.32.3) (2024.7.4)
Requirement already satisfied: soupsieve>1.2 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from beautifulsoup4==4.12.3) (2.5)
Requirement already satisfied: numpy>=1.26.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pandas==2.2.2) (2.0.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pandas==2.2.2) (2.9.0)
Requirement already satisfied: pytz>=2020.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pandas==2.2.2) (2024.1)
Requirement already satisfied: arabic-reshaper>=3.0.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (3.0.0)
Requirement already satisfied: html5lib>=1.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (1.1)
Requirement already satisfied: Pillow>=8.1.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (10.4.0)
Requirement already satisfied: pyHanko>=0.12.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (0.25.0)
Requirement already satisfied: pyhanko-certvalidator>=0.19.5 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (0.26.3)
Requirement already satisfied: pypdf>=3.1.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (4.2.0)
Requirement already satisfied: python-bidi>=0.4.2 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (0.4.2)
Requirement already satisfied: reportlab<5,>=4.0.4 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (4.2.2)
Requirement already satisfied: svglib>=1.2.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from xhtml2pdf==0.2.16) (1.5.1)
Requirement already satisfied: six>=1.9 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from html5lib>=1.1->xhtml2pdf==0.2.16) (1.16.0)
Requirement already satisfied: webencodings in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from html5lib>=1.1->xhtml2pdf==0.2.16) (0.5.1)
Requirement already satisfied: asn1crypto>=1.5.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (1.5.1)
Requirement already satisfied: qrcode>=7.3.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (7.4.2)
Requirement already satisfied: tzlocal>=4.3 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (5.2)
Requirement already satisfied: click>=8.1.3 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (8.1.7)
Requirement already satisfied: pyyaml>=6.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (6.0.1)
Requirement already satisfied: cryptography>=42.0.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyHanko>=0.12.1->xhtml2pdf==0.2.16) (42.0.8)
Requirement already satisfied: oscrypto>=1.1.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyhanko-certvalidator>=0.19.5->xhtml2pdf==0.2.16) (1.3.0)
Requirement already satisfied: uritools>=3.0.1 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from pyhanko-certvalidator>=0.19.5->xhtml2pdf==0.2.16) (4.0.3)
Requirement already satisfied: chardet in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from reportlab<5,>=4.0.4->xhtml2pdf==0.2.16) (5.2.0)
Requirement already satisfied: lxml in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from svglib>=1.2.1->xhtml2pdf==0.2.16) (5.2.2)
Requirement already satisfied: tinycss2>=0.6.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from svglib>=1.2.1->xhtml2pdf==0.2.16) (1.3.0)
Requirement already satisfied: cssselect2>=0.2.0 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from svglib>=1.2.1->xhtml2pdf==0.2.16) (0.7.0)
Requirement already satisfied: colorama in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from click>=8.1.3->pyHanko>=0.12.1->xhtml2pdf==0.2.16) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from cryptography>=42.0.1->pyHanko>=0.12.1->xhtml2pdf==0.2.16) (1.16.0)
Requirement already satisfied: typing-extensions in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from qrcode>=7.3.1->pyHanko>=0.12.1->xhtml2pdf==0.2.16) (4.12.2)
Requirement already satisfied: pypng in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from qrcode>=7.3.1->pyHanko>=0.12.1->xhtml2pdf==0.2.16) (0.20220715.0)
Requirement already satisfied: pycparser in c:\users\ashar\anaconda3\envs\py312sec\lib\site-packages (from cffi>=1.12->cryptography>=42.0.1->pyHanko>=0.12.1->xhtml2pdf==0.2.16) (2.22)
Note: you may need to restart the kernel to use updated packages.

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

# Obtaining Rulemaking File Numbers

In [2]:
def get_rules_df(url):
    # Send a GET request to the URL
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    }
    response = requests.get(url, headers=headers)

    # Check if the request was successful
    if response.status_code == 200:
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Find the table element
        table = soup.find('table')

        # Extract headers
        headers = [header.text.strip() for header in table.find_all('th')]

        # Extract rows
        rows = []
        for row in table.find_all('tr'):
            columns = row.find_all('td')
            if columns:
                rows.append([column.text.strip() for column in columns])

        # Create a DataFrame using the headers and rows
        df = pd.DataFrame(rows, columns=headers)
        return df
    else:
        print("Failed to retrieve the webpage. Status code:", response.status_code)
        return pd.DataFrame()

In [3]:
# URL of the SEC rulemaking activity page
urls = [f'https://www.sec.gov/rules-regulations/rulemaking-activity?page={x}' for x in range(10)]

dfs = []

for x in urls:
    dfs = dfs+[get_rules_df(x)]

df=pd.concat(dfs).reset_index(drop=True)

In [4]:
# Cleaning up Status Column
df[["Status", "Status Note"]] = df["Status"].str.replace("\n                      ", " ").str.split("\n                  \n", expand = True)

In [5]:
# Removing rows with no 
df = df.loc[df["File Number"]!=""]

In [6]:
df.head()

,Issue Date,File Number,Rulemaking,Status,Status Note
0,"July 1, 2024",S7-16-23,Registration for Index-Linked Annuities; Amend...,Final Rule,Registration for Index-Linked Annuities and Re...
2,"June 21, 2024",S7-05-23,Regulation S-P: Privacy of Consumer Financial ...,Final Rule,Final rule; correction\n\n\n34-100155A \n\n\n\...
3,"May 16, 2024",S7-05-23,Regulation S-P: Privacy of Consumer Financial ...,Final Rule,Regulation S-P: Privacy of Consumer Financial ...
4,"May 13, 2024",S7-2024-02,Customer Identification Programs for Registere...,Proposed Rule,Customer Identification Programs for Registere...
5,"March 27, 2024",S7-13-23,Exemption for Certain Investment Advisers Oper...,Final Rule,Exemption for Certain Investment Advisers Oper...

In [7]:
# We only need unique file numbers because there is only one web-page for 
file_nos = df[["File Number"]].drop_duplicates()

In [9]:
file_nos.shape

(221, 1)

In [10]:
file_nos["File Number Url String1"] = file_nos["File Number"].str.lower()
file_nos["File Number Url String2"] = file_nos["File Number Url String1"].str.replace("-","")

In [11]:
file_nos.head()

  File Number File Number Url String1 File Number Url String2
0    S7-16-23                s7-16-23                  s71623
2    S7-05-23                s7-05-23                  s70523
4  S7-2024-02              s7-2024-02                s7202402
5    S7-13-23                s7-13-23                  s71323
6    S7-21-21                s7-21-21                  s72121

# Obtaining Comment Documents Links

In [86]:
comment_urls = (
    "https://www.sec.gov/comments/"
    +file_nos["File Number Url String1"]
    +"/"
    +file_nos["File Number Url String2"]
    ).to_list()

In [87]:
comment_urls[0]

'https://www.sec.gov/comments/s7-16-23/s71623'

In [94]:
def get_comments_table(url):
    # Send a GET request to the URL
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
    }
    full_url = url+".htm"
    response = requests.get(full_url, headers=headers)

    # Check if the request was successful
    if response.status_code != 200:
        full_url = url+".shtml"
        response = requests.get(full_url, headers=headers)

    # Check if the request was successful
    if response.status_code == 200:
        print(full_url)
        # Parse the HTML content using BeautifulSoup
        soup = BeautifulSoup(response.content, 'html.parser')

        # Obtain all the rows and the associated links
        rows = []
        for row in soup.find_all('tr'):
            a = row.find('a', href=True)
            columns = row.find_all('td')
            if columns:
                if a is not None:
                    rows.append([column.text.strip() for column in columns]+[a['href']])
                else:
                    rows.append([column.text.strip() for column in columns]+[None])

        # Create a DataFrame
        df = pd.DataFrame(rows)

        # Dropping rows with no comment document
        df = df.dropna(subset=2, axis=0, how="all")

        # Keep rows before the "SEC Staff Studies and Reports" row
        check = df[df.iloc[:,0].str.startswith("SEC Staff Studies and Reports")].index
        if len(check) > 0:
            index_studies = check[0]
            df = df.loc[(df.index<index_studies)]

        
        # Keep rows before the "Meetings with SEC Officials" row
        check = df[df.iloc[:,0].str.startswith("Meetings with SEC Officials")].index
        if len(check) > 0:
            index_meetings = check[0]
            df = df.loc[(df.index<index_meetings)]

        # Keeping only rows with comments and the first three columns
        df = df.loc[df.iloc[:,2].str.contains("comments")].iloc[:,0:3]

        # Renaming the columns
        df.columns = ["Date", "Name", "Sublink"]
        
        return df

    else:
        print(full_url)
        print("Failed to retrieve the webpage. Status code:", response.status_code)
        return pd.DataFrame()

In [95]:
# URL of the SEC Rulemaking Comments
comm_dfs = []
for x in comment_urls:
    comm_dfs = comm_dfs+[get_comments_table(x)]

comm_df=pd.concat(comm_dfs).reset_index(drop=True)

# Creating the Link columns
comm_df["Link"] = "https://www.sec.gov"+comm_df["Sublink"]

https://www.sec.gov/comments/s7-16-23/s71623.htm
https://www.sec.gov/comments/s7-05-23/s70523.htm
https://www.sec.gov/comments/s7-2024-02/s7202402.htm
https://www.sec.gov/comments/s7-13-23/s71323.htm
https://www.sec.gov/comments/s7-21-21/s72121.htm
https://www.sec.gov/comments/s7-29-22/s72922.htm
https://www.sec.gov/comments/s7-10-22/s71022.htm
https://www.sec.gov/comments/s7-02-23/s70223.htm
https://www.sec.gov/comments/s7-2024-01/s7202401.htm
https://www.sec.gov/comments/s7-22-22/s72222.htm
https://www.sec.gov/comments/s7-12-22/s71222.htm
https://www.sec.gov/comments/s7-13-22/s71322.htm
https://www.sec.gov/comments/s7-23-22/s72322.htm
https://www.sec.gov/comments/s7-01-23/s70123.htm
https://www.sec.gov/comments/s7-21-22/s72122.htm
https://www.sec.gov/comments/s7-14-22/s71422.htm
https://www.sec.gov/comments/s7-18-23/s71823.htm
https://www.sec.gov/comments/s7-08-22/s70822.htm
https://www.sec.gov/comments/s7-18-21/s71821.htm
https://www.sec.gov/comments/s7-06-22/s70622.htm
https://www.sec.gov/comments/s7-03-23/s70323.htm
https://www.sec.gov/comments/s7-16-22/s71622.htm
https://www.sec.gov/comments/s7-15-23/s71523.htm
https://www.sec.gov/comments/s7-04-23/s70423.htm
https://www.sec.gov/comments/s7-03-22/s70322.htm
https://www.sec.gov/comments/s7-05-15/s70515.htm
https://www.sec.gov/comments/s7-12-23/s71223.htm
https://www.sec.gov/comments/s7-09-22/s70922.htm
https://www.sec.gov/comments/s7-11-23/s71123.htm
https://www.sec.gov/comments/s7-22-21/s72221.htm
https://www.sec.gov/comments/s7-32-10/s73210.htm
https://www.sec.gov/comments/s7-11-22/s71122.htm
https://www.sec.gov/comments/s7-10-23/s71023.htm
https://www.sec.gov/comments/s7-01-22/s70122.htm
https://www.sec.gov/comments/s7-02-22/s70222.htm
https://www.sec.gov/comments/s7-08-23/s70823.htm
https://www.sec.gov/comments/s7-07-23/s70723.htm
https://www.sec.gov/comments/s7-06-23/s70623.htm
https://www.sec.gov/comments/s7-05-22/s70522.htm
https://www.sec.gov/comments/s7-32-22/s73222.htm
https://www.sec.gov/comments/s7-31-22/s73122.htm
https://www.sec.gov/comments/s7-30-22/s73022.htm
https://www.sec.gov/comments/s7-20-21/s72021.htm
https://www.sec.gov/comments/s7-26-22/s72622.htm
https://www.sec.gov/comments/s7-11-21/s71121.htm
https://www.sec.gov/comments/s7-25-22/s72522.htm
https://www.sec.gov/comments/s7-12-15/s71215.htm
https://www.sec.gov/comments/s7-09-20/s70920.htm
https://www.sec.gov/comments/s7-19-21/s71921.htm
https://www.sec.gov/comments/s7-32-10, s7-18-21, s7-21-21, s7-22-21, s7-03-22, s7-08-22, s7-09-22, s7-10-22, s7-13-22, s7-16-22, s7-17-22, s7-18-22/s73210, s71821, s72121, s72221, s70322, s70822, s70922, s71022, s71322, s71622, s71722, s71822.shtml
Failed to retrieve the webpage. Status code: 503
https://www.sec.gov/comments/s7-07-22/s70722.htm
https://www.sec.gov/comments/s7-07-15/s70715.htm
https://www.sec.gov/comments/s7-20-22/s72022.htm
https://www.sec.gov/comments/s7-17-21/s71721.htm
https://www.sec.gov/comments/s7-15-21/s71521.htm
https://www.sec.gov/comments/s7-24-20/s72420.htm
https://www.sec.gov/comments/s7-17-22/s71722.htm
https://www.sec.gov/comments/s7-04-22/s70422.htm
https://www.sec.gov/comments/s7-03-21/s70321.htm
https://www.sec.gov/comments/s7-24-16/s72416.htm
https://www.sec.gov/comments/s7-16-21/s71621.htm
https://www.sec.gov/comments/s7-20-19/s72019.htm
https://www.sec.gov/comments/s7-14-11/s71411.shtml
https://www.sec.gov/comments/s7-21-19/s72119.htm
https://www.sec.gov/comments/s7-24-19/s72419.htm
https://www.sec.gov/comments/s7-08-11/s70811.shtml
https://www.sec.gov/comments/s7-11-20/s71120.htm
https://www.sec.gov/comments/s7-03-20/s70320.htm
https://www.sec.gov/comments/s7-07-20/s70720.htm
https://www.sec.gov/comments/s7-19-20/s71920.htm
https://www.sec.gov/comments/s7-18-20/s71820.htm
https://www.sec.gov/comments/s7-01-20/s70120.htm
https://www.sec.gov/comments/s7-19-15/s71915.shtml
https://www.sec.gov/comments/s7-05-20/s70520.htm
https://www.sec.gov/comments/s7-24-15/s72415.shtml
https://www.sec.gov/comments/s7-09-19/s70919.htm
https://www.sec.gov/comments/s7-26-19/s72619.htm
https://www.sec.gov/comments/s7-27-18/s72718.htm
https://www.sec.gov/comments/s7-12-20/s71220.htm
https://www.sec.gov/comments/s7-16-18/s71618.htm
https://www.sec.gov/comments/s7-23-19/s72319.htm
https://www.sec.gov/comments/s7-14-19/s71419.htm
https://www.sec.gov/comments/s7-02-17/s70217.htm
https://www.sec.gov/comments/s7-25-19/s72519.htm
https://www.sec.gov/comments/s7-11-19/s71119.htm
https://www.sec.gov/comments/s7-10-20/s71020.htm
https://www.sec.gov/comments/s7-15-19/s71519.htm
https://www.sec.gov/comments/s7-02-16/s70216.htm
https://www.sec.gov/comments/s7-22-19/s72219.htm
https://www.sec.gov/comments/s7-08-20/s70820.htm
https://www.sec.gov/comments/s7-19-19/s71919.htm
https://www.sec.gov/comments/s7-02-20/s70220.htm
https://www.sec.gov/comments/s7-05-19/s70519.htm
https://www.sec.gov/comments/s7-13-19/s71319.htm
https://www.sec.gov/comments/s7-23-16/s72316.htm
https://www.sec.gov/comments/s7-03-19/s70319.htm
https://www.sec.gov/comments/s7-06-19/s70619.htm
https://www.sec.gov/comments/s7-23-18/s72318.htm
https://www.sec.gov/comments/s7-19-18/s71918.htm
https://www.sec.gov/comments/s7-07-19/s70719.htm
https://www.sec.gov/comments/s7-28-18/s72818.htm
https://www.sec.gov/comments/s7-15-18/s71518.htm
https://www.sec.gov/comments/s7-01-19/s70119.htm
https://www.sec.gov/comments/s7-05-14/s70514.shtml
https://www.sec.gov/comments/s7-14-18/s71418.htm
https://www.sec.gov/comments/s7-09-17/s70917.htm
https://www.sec.gov/comments/s7-22-18/s72218.htm
https://www.sec.gov/comments/s7-08-17/s70817.htm
https://www.sec.gov/comments/s7-30-18/s73018.htm
https://www.sec.gov/comments/s7-08-12/s70812.shtml
https://www.sec.gov/comments/s7-08-19/s70819.htm
https://www.sec.gov/comments/s7-10-18/s71018.htm
https://www.sec.gov/comments/s7-21-18/s72118.htm
https://www.sec.gov/comments/s7-07-18/s70718.htm
https://www.sec.gov/comments/s7-08-18/s70818.htm
https://www.sec.gov/comments/s7-14-16/s71416.htm
https://www.sec.gov/comments/s7-02-19/s70219.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-01-15/s70115.shtml
https://www.sec.gov/comments/s7-29-18/s72918.htm
https://www.sec.gov/comments/s7-14-15/s71415.shtml
https://www.sec.gov/comments/s7-05-18/s70518.htm
https://www.sec.gov/comments/s7-11-18/s71118.htm
https://www.sec.gov/comments/s7-08-15, s7-04-18/s70815, s70418.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-23-15/s72315.shtml
https://www.sec.gov/comments/s7-10-16/s71016.htm
https://www.sec.gov/comments/s7-01-17/s70117.htm
https://www.sec.gov/comments/s7-15-16/s71516.htm
https://www.sec.gov/comments/s7-18-18/s71818.htm
https://www.sec.gov/comments/s7-17-18/s71718.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-12-16/s71216.htm
https://www.sec.gov/comments/s7-03-17/s70317.htm
https://www.sec.gov/comments/s7-04-18/s70418.htm
https://www.sec.gov/comments/s7-08-15/s70815.shtml
https://www.sec.gov/comments/s7-09-18/s70918.htm
https://www.sec.gov/comments/s7-03-18/s70318.htm
https://www.sec.gov/comments/s7-05-17/s70517.htm
https://www.sec.gov/comments/s7-09-14/s70914.shtml
https://www.sec.gov/comments/s7-06-17/s70617.htm
https://www.sec.gov/comments/s7-07-13/s70713.shtml
https://www.sec.gov/comments/s7-22-16/s72216.htm
https://www.sec.gov/comments/s7-19-16/s71916.htm
https://www.sec.gov/comments/s7-22-15/s72215.shtml
https://www.sec.gov/comments/s7-26-11/s72611.shtml
https://www.sec.gov/comments/s7-12-14/s71214.shtml
https://www.sec.gov/comments/s7-16-15/s71615.shtml
https://www.sec.gov/comments/s7-03-14/s70314.shtml
https://www.sec.gov/comments/s7-15-15/s71515.shtml
https://www.sec.gov/comments/s7-09-15/s70915.shtml
https://www.sec.gov/comments/s7-03-15/s70315.shtml
https://www.sec.gov/comments/s7-18-15/s71815.shtml
https://www.sec.gov/comments/s7-13-16/s71316.htm
https://www.sec.gov/comments/s7-11-16/s71116.htm
https://www.sec.gov/comments/s7-25-15/s72515.shtml
https://www.sec.gov/comments/s7-03-16/s70316.htm
https://www.sec.gov/comments/s7-03-11/s70311.shtml
https://www.sec.gov/comments/s7-09-16/s70916.htm
https://www.sec.gov/comments/s7-30-11/s73011.shtml
https://www.sec.gov/comments/s7-07-16/s70716.htm
https://www.sec.gov/comments/s7-25-11/s72511.shtml
https://www.sec.gov/comments/s7-06-16/s70616.htm
https://www.sec.gov/comments/s7-05-16/s70516.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-27-15/s72715.shtml
https://www.sec.gov/comments/s7-06-15/s70615.shtml
https://www.sec.gov/comments/s7-01-16/s70116.htm
https://www.sec.gov/comments/s7-01-13/s70113.shtml
https://www.sec.gov/comments/s7-26-15/s72615.shtml
https://www.sec.gov/comments/s7-09-13/s70913.shtml
https://www.sec.gov/comments/s7-16-15, s7-08-15/s71615, s70815.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-07-11/s70711.shtml
https://www.sec.gov/comments/s7-40-11/s74011.shtml
https://www.sec.gov/comments/s7-07-14/s70714.shtml
https://www.sec.gov/comments/s7-13-15/s71315.shtml
https://www.sec.gov/comments/s7-16-11/s71611.shtml
https://www.sec.gov/comments/s7-11-13/s71113.shtml
https://www.sec.gov/comments/s7-35-10/s73510.shtml
https://www.sec.gov/comments/s7-34-10/s73410.shtml
https://www.sec.gov/comments/s7-08-10/s70810.shtml
https://www.sec.gov/comments/s7-23-07/s72307.shtml
https://www.sec.gov/comments/s7-18-11/s71811.shtml
https://www.sec.gov/comments/s7-03-13/s70313.shtml
https://www.sec.gov/comments/s7-02-13/s70213.shtml
https://www.sec.gov/comments/s7-12-10/s71210.shtml
https://www.sec.gov/comments/s7-01-14/s70114.shtml
https://www.sec.gov/comments/s7-45-10/s74510.shtml
https://www.sec.gov/comments/s7-7-11/s7711.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-15-11/s71511.shtml
https://www.sec.gov/comments/s7-41-11/s74111.shtml
https://www.sec.gov/comments/s7-06-13/s70613.shtml
https://www.sec.gov/comments/s7-19-10/s71910.shtml
https://www.sec.gov/comments/s7-08-07/s70807.shtml
https://www.sec.gov/comments/s7-23-11/s72311.shtml
https://www.sec.gov/comments/s7-07-12/s70712.shtml
https://www.sec.gov/comments/s7-21-11/s72111.shtml
https://www.sec.gov/comments/s7-02-13, s7-34-10, s7-40-11/s70213, s73410, s74011.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-27-10, s7-32-10, s7-34-10, s7-35-10, s7-43-10, s7-03-11, s7-06-11, s7-08-11, s7-25-11, s7-40-11, s7-05-12, s7-08-12/s72710, s73210, s73410, s73510, s74310, s70311, s70611, s70811, s72511, s74011, s70512, s70812.shtml
Failed to retrieve the webpage. Status code: 404
https://www.sec.gov/comments/s7-02-12/s70212.shtml
https://www.sec.gov/comments/s7-29-11/s72911.shtml
https://www.sec.gov/comments/s7-11-11/s71111.shtml
https://www.sec.gov/comments/s7-44-10/s74410.shtml
https://www.sec.gov/comments/s7-42-10/s74210.shtml
https://www.sec.gov/comments/s7-40-10/s74010.shtml
https://www.sec.gov/comments/s7-11-10/s71110.shtml
https://www.sec.gov/comments/s7-06-12/s70612.shtml
https://www.sec.gov/comments/s7-13-11/s71311.shtml
https://www.sec.gov/comments/s7-18-09/s71809.shtml
https://www.sec.gov/comments/s7-36-10/s73610.shtml
https://www.sec.gov/comments/s7-39-10/s73910.shtml
https://www.sec.gov/comments/s7-22-11/s72211.shtml
https://www.sec.gov/comments/s7-04-11/s70411.shtml
https://www.sec.gov/comments/s7-17-11/s71711.shtml
https://www.sec.gov/comments/s7-31-11/s73111.shtml
https://www.sec.gov/comments/s7-38-11/s73811.htm
https://www.sec.gov/comments/s7-41-10/s74110.shtml
https://www.sec.gov/comments/s7-05-11/s70511.shtml
https://www.sec.gov/comments/s7-10-09/s71009.shtml
https://www.sec.gov/comments/s7-19-11/s71911.shtml
https://www.sec.gov/comments/s7-35-11/s73511.shtml
https://www.sec.gov/comments/s7-34-11/s73411.shtml
https://www.sec.gov/comments/s7-33-11/s73311.shtml
https://www.sec.gov/comments/s7-24-10/s72410.shtml
https://www.sec.gov/comments/s7-02-11/s70211.shtml

In [102]:
comm_df.head(2)

,Date,Name,Sublink,Link
0,"May 2, 2024","Michele Abate, Head of Securities Products & F...",/comments/s7-16-23/s71623-1235274.htm,https://www.sec.gov/comments/s7-16-23/s71623-1...
1,"Apr. 5, 2024","Ronald Coenen Jr., Partner, Eversheds Sutherland",/comments/s7-16-23/s71623-1167914.htm,https://www.sec.gov/comments/s7-16-23/s71623-1...

In [97]:
# Verifying that there are only 3 file types for Comments: htm, pdf, html
comm_df["Sublink"].str.split(".", expand=True)[1].unique()

array(['htm', 'pdf', 'html', 'txt', 'pdff'], dtype=object)

In [104]:
# There is no PDFF file format. So, we will use PDF instead
comm_df["Sublink"] = comm_df["Sublink"].str.replace(".pdff", ".pdf")
comm_df["Link"] = comm_df["Link"].str.replace(".pdff", ".pdf")

In [108]:
# Verifying that there are only 3 file types for Comments: htm, pdf, html
comm_df["Sublink"].str.split(".", expand=True)[1].value_counts()

1
htm     34383
pdf     22278
html       42
txt         8
Name: count, dtype: int64

# Downloading HTML, HTM Pages as PDFs

# Downloading Only PDF Comment Documents

In [225]:
import os

In [229]:
if not os.path.exists("pdfs"):
    os.mkdir("pdfs")

def download_pdf(url):
    headers = {
            "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"
        }
    response = requests.get(url, headers=headers)

    with open(os.path.join("pdfs",url.split("/")[-1]), 'wb') as file:
        # Write the content of the response (the downloaded file) to the local file
        file.write(response.content)
        print(f'{url.split("/")[-1]}: Done')

In [230]:
[download_pdf(x) for x in comm_df["Link"] if "pdf" in x]

s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done
s71623-303459-781322.pdf: Done
s71623-303279-781182.pdf: Done
s71623-297139-724642.pdf: Done
s71623-291099-709682.pdf: Done
s71623-292039-711342.pdf: Done
s71623-266579-640482.pdf: Done
s71623-267439-638642.pdf: Done
s71822-445979-1141042.pdf: Done
s71623-321139-834462.pdf: Done
s71623-303499-781402.pdf: Done
s71623-303559-781542.pdf: Done
s71623-303339-781222.pdf: Done
s71623-303439-781302.pdf: Done

ChunkedEncodingError: ('Connection broken: IncompleteRead(184683 bytes read, 93560 more expected)', IncompleteRead(184683 bytes read, 93560 more expected))